version: "3.7"

services:
    sistema_gestao:
        container_name: sistema-gestao
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - sistema-getao-network
    # nginx
    nginx:
        container_name: servidor-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - sistema-getao-network
    mysql:
        container_name: banco-mysql
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - sistema-getao-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - mysql
        restart: always
        environment:
            - PMA_ARBITRARY=1
        ports:
            - 9080:80
        networks:
            - sistema-getao-network

networks:
    sistema-getao-network:
        driver: bridge

# PHPMYADMIN info no file
# servidor: mysql
# user: root
# pass: root

# EXECUTAR KEY COMO ROOT = 0
# docker exec -u 0 name_docker_app php artisan key:generate